cover:
  - platform: mqtt
    name: "Estores Cozinha"
    command_topic: "home/kitchen/window/set"
    state_topic: "home/kitchen/window/state"
    qos: 0
    retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    optimistic: false
